### ISSUE TITLE
BeaconService:terminate

### ISSUE THREAD

**Issue by jjochen** [beaconinside/beaconinside-ios-sdk#2]
In the [Readme](https://github.com/beaconinside/beaconinside-ios-sdk/blob/master/README.md#opt-out---stopping-the-beacon-service) it says: 
"To gracefully stop the monitoring you should always use `BeaconService:terminate`". 
However `- (void)terminate` is a private method of `BeaconService`.

**Comment by rabschi** [comment]
Thanks, fixed with v1.0.1.
