### ISSUE TITLE
Duplicate GitHub repositories

### ISSUE THREAD

**Issue by jjochen** [beaconinside/beaconinside-ios-sdk#3]
What is the difference between these two repositories?
https://github.com/beaconinside/beaconinside-ios-sdk
https://github.com/beaconinside/BeaconService

On http://www.beaconinside.com/developer-documentation is a link to the first, but cocoapods links to the second one.

**Comment by rabschi** [comment]
Hello Jochen, /BeaconService repository is purely for the CocoaPod release and the other is the static library that can directly be integrated into your project. Both repos contain sample projects that show how the integration can be done.

/BeaconService is lagging 1 release version but will catch up tomorrow.
